name: Rebuild tag from main (multi-arch)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Semver WITHOUT the leading v (e.g. 8.0.10)"
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: rebuild-main-to-tag-${{ inputs.tag }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: tags
        run: |
          echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
          echo "VTAG=v${{ inputs.tag }}" >> $GITHUB_ENV
          echo "tags=ghcr.io/${{ github.repository }}:${{ inputs.tag }},ghcr.io/${{ github.repository }}:v${{ inputs.tag }}" >> $GITHUB_OUTPUT

      - name: Build & push (linux/amd64, linux/arm64)
        id: buildpush
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: true
          sbom: true
          no-cache: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.TAG }}
            ghcr.io/${{ github.repository }}:${{ env.VTAG }}

      - name: Show what we pushed
        run: |
          echo "Digest: ${{ steps.buildpush.outputs.digest }}"
          echo "Tags:"
          echo "  ghcr.io/${{ github.repository }}:${{ env.TAG }}"
          echo "  ghcr.io/${{ github.repository }}:${{ env.VTAG }}"
          docker buildx imagetools inspect ghcr.io/${{ github.repository }}:${{ env.TAG }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign the images (keyless OIDC)
        env:
          DIGEST: ${{ steps.buildpush.outputs.digest }}
        run: |
          set -euo pipefail
          images="ghcr.io/${{ github.repository }}:${{ env.TAG }}@${DIGEST} ghcr.io/${{ github.repository }}:${{ env.VTAG }}@${DIGEST}"
          echo "Signing: $images"
          cosign sign --yes $images
